package:
  name: pyocct
  version: "7.2.0.1"

source:
  path: ../..

build:
  number: 0
  features:
    - vc14 # [win and py35]
    - vc14 # [win and py36]

requirements:
  build:
    - python
    - vc 14 # [win]
    - cmake
    - ninja
    - pybind11
    - occt ==7.2.0
    - vtk ==8.1.0
    - smesh ==8.3.*  # [win]
    - netgen ==6.2.* # [win]

  run:
    - python
    - wxpython       # [win]
    - wxpython ==4.0.1 py36h37420ed_1 # [linux]
    - vc 14 # [win]
    - occt ==7.2.*
    - vtk ==8.1.*
    - smesh ==8.3.*  # [win]
    - netgen ==6.2.* # [win]

test:
  imports:
    - OCCT
    - OCCT.TopoDS

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE
  description: Python bindings for OpenCASCADE geometry kernel
               and SMESH meshing library.
