# Sets the build environment.
sudo: required

language: cpp

services:
  - docker

env:
  DOCKER_IMAGE=shrdluk/pyocct-compat

cache:
  directories:
    - $HOME/mybuild

before_install:
  - python git-restore-mtime.py
  - docker pull $DOCKER_IMAGE
  - bash update_docker.sh

script:
  - docker run -v $PWD:/app/project -v $HOME/mybuild:/app/mybuild $DOCKER_IMAGE /bin/bash -c "cd /app/project; /bin/bash do_build.sh $ANA_USER $ANA_TOKEN"

after_success:
  - bash reschedule-if-required.sh
